In [4]:
#importing the numpy package into the project
import numpy as np
ls=[1,2,3]
ls
np.array(ls)

array([1, 2, 3])

In [5]:
mls=[[1,2,3],[4,5,6]]
type(mls)

list

In [6]:
mls=[[1,2,3],[4,5,6]]
np.array(mls)

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
mls=[[1,2,3],[4,5,6]]
print(mls)
print(np.array(mls))

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


In [8]:
mls=[1,2,3],[4,5,6],[7,8,9]
print(mls)
print(np.array(mls))

([1, 2, 3], [4, 5, 6], [7, 8, 9])
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [2]:

#zeros method
import numpy as np
s=np.zeros(4)
print(s)
p=np.zeros((2,4))
print(p)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [98]:
s=np.zeros((4,4))
s+=5
s

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [21]:

#ones method
np.ones(4)
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [102]:
#linspace() #to split range functions
#it will take 3 parameters 1st intital value 2nd value before the last one and 3rd is interval value
s=np.linspace(0,10)
print(s)
p=np.linspace(0,10,5)
print(p)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
[ 0.   2.5  5.   7.5 10. ]


In [24]:
np.linspace(0,7,70)

array([0.        , 0.10144928, 0.20289855, 0.30434783, 0.4057971 ,
       0.50724638, 0.60869565, 0.71014493, 0.8115942 , 0.91304348,
       1.01449275, 1.11594203, 1.2173913 , 1.31884058, 1.42028986,
       1.52173913, 1.62318841, 1.72463768, 1.82608696, 1.92753623,
       2.02898551, 2.13043478, 2.23188406, 2.33333333, 2.43478261,
       2.53623188, 2.63768116, 2.73913043, 2.84057971, 2.94202899,
       3.04347826, 3.14492754, 3.24637681, 3.34782609, 3.44927536,
       3.55072464, 3.65217391, 3.75362319, 3.85507246, 3.95652174,
       4.05797101, 4.15942029, 4.26086957, 4.36231884, 4.46376812,
       4.56521739, 4.66666667, 4.76811594, 4.86956522, 4.97101449,
       5.07246377, 5.17391304, 5.27536232, 5.37681159, 5.47826087,
       5.57971014, 5.68115942, 5.7826087 , 5.88405797, 5.98550725,
       6.08695652, 6.1884058 , 6.28985507, 6.39130435, 6.49275362,
       6.5942029 , 6.69565217, 6.79710145, 6.89855072, 7.        ])

In [104]:
#identity matrix
p=np.eye(4)
print(p)
p+=2
print(p)
p*=2
print(p)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[3. 2. 2. 2.]
 [2. 3. 2. 2.]
 [2. 2. 3. 2.]
 [2. 2. 2. 3.]]
[[6. 4. 4. 4.]
 [4. 6. 4. 4.]
 [4. 4. 6. 4.]
 [4. 4. 4. 6.]]


In [26]:
np.random.rand(4)

array([0.14769911, 0.77515622, 0.37075229, 0.78355911])

In [27]:
np.random.rand(3)

array([0.35847616, 0.61314109, 0.78299935])

In [30]:
np.random.rand(10,10)

array([[0.30001617, 0.68965532, 0.62604989, 0.39587479, 0.46178209,
        0.80925895, 0.58556561, 0.85346193, 0.14382511, 0.26600962],
       [0.9670346 , 0.83251136, 0.69700805, 0.76228708, 0.04498152,
        0.11720236, 0.40618985, 0.9729197 , 0.94858011, 0.56074048],
       [0.70694783, 0.41314231, 0.19188205, 0.61988656, 0.55633129,
        0.18267642, 0.85558717, 0.69318806, 0.29234521, 0.6862917 ],
       [0.12890362, 0.09775346, 0.75604903, 0.52623083, 0.42054913,
        0.18131864, 0.98138597, 0.41678486, 0.42191007, 0.26268641],
       [0.7002487 , 0.82717647, 0.75573911, 0.23527149, 0.19165888,
        0.98976959, 0.22877266, 0.93602715, 0.89516031, 0.11768892],
       [0.01181947, 0.01171784, 0.64370438, 0.71930761, 0.74795836,
        0.73686278, 0.19207027, 0.28159439, 0.08527216, 0.31166329],
       [0.61134092, 0.74722798, 0.36547468, 0.05901921, 0.81931607,
        0.88602224, 0.5868569 , 0.75842737, 0.24015326, 0.97625155],
       [0.91001973, 0.32564693, 0.8156735

In [32]:
#by using this"?" we can get to know what that function does(description)
np.arange?
np.zeros?
rehspe,randimt

In [33]:
#reshape
#10 should be multiple of 2,5
b=np.arange(10).reshape(2,5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [105]:
b=np.arange(24).reshape(3,4,2)
b
c=np.arange(24).reshape(6,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [109]:
b=np.arange(24).reshape(6,2,2)
b
s=np.arange(100).reshape(50,2)
s

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49],
       [50, 51],
       [52, 53],
       [54, 55],
       [56, 57],
       [58, 59],
       [60, 61],
       [62, 63],
       [64, 65],
       [66, 67],
       [68, 69],
       [70, 71],
       [72, 73],
       [74, 75],
       [76, 77],
       [78, 79],
       [80, 81],
       [82, 83],
       [84, 85],
       [86, 87],
       [88, 89],
       [90, 91],
       [92, 93],
       [94, 95],
       [96, 97],
       [98, 99]])

In [39]:
np.arange(1000).reshape(10,10,10)

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165,

In [40]:
np.arange(1000).reshape(100,10)

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [41]:
np.arange(10000).reshape(100,100)

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [46]:
#we get any random value in thar range 
np.random.randint(1,101)

3

In [47]:
np.random.randint(1,501,20)

array([ 79, 321, 312, 462, 362, 299, 115, 404, 460, 212, 319, 351, 132,
       159, 236,  77, 247, 241, 471, 213])

In [111]:
p=np.random.randint(1,501,20)
p

array([ 38, 455, 317, 180, 196, 112, 461, 263,  89, 147, 354, 351, 412,
       297, 230, 207, 253, 224, 475,  79])

In [50]:
a=np.array([[1,2],[2,3]])
b=np.array([[2,1],[3,2]])
a*b

array([[2, 2],
       [6, 6]])

In [51]:
a=np.array([[1,2],[2,3]])
b=np.array([[2,1],[3,2]])
a@b

array([[ 8,  5],
       [13,  8]])

In [52]:
a=np.array([[1,3],[2,1]])
b=np.array([[2,2],[3,3]])
a*b

array([[2, 6],
       [6, 3]])

In [53]:
a=np.array([[1,3],[2,1]])
b=np.array([[2,2],[3,3]])


a@b

array([[11, 11],
       [ 7,  7]])

In [55]:
a=np.array([[1,3],[2,1]])
b=np.array([[2,2],[3,3]])
c=a.dot(b)
print(c)

[[11 11]
 [ 7  7]]


In [56]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [57]:
np.random.randint(50,10)

array([[0.68834321, 0.29231342, 0.27776336, 0.36328075, 0.46868006,
        0.42587694, 0.62000168, 0.97508352, 0.14468272, 0.18696416],
       [0.80235743, 0.04647313, 0.37935632, 0.98144498, 0.6541499 ,
        0.91372495, 0.59727512, 0.57851224, 0.64092451, 0.0843874 ],
       [0.87376761, 0.72101385, 0.40241078, 0.9158279 , 0.54679369,
        0.57520613, 0.67668013, 0.52595835, 0.90822478, 0.71102149],
       [0.73610594, 0.56244654, 0.64397317, 0.25952336, 0.59851156,
        0.97243024, 0.68982685, 0.43061251, 0.5153153 , 0.6347119 ],
       [0.99398064, 0.59991451, 0.06503822, 0.09200203, 0.04722758,
        0.74415902, 0.98568311, 0.50199214, 0.06207389, 0.49793172],
       [0.28317271, 0.89773743, 0.00565933, 0.16599314, 0.91210923,
        0.12316454, 0.80195454, 0.46047258, 0.36504388, 0.97851284],
       [0.14112453, 0.96828616, 0.35505405, 0.58135854, 0.25090259,
        0.18579784, 0.16644047, 0.05459812, 0.44854352, 0.38399567],
       [0.28349684, 0.94343437, 0.2242510

In [59]:
r=np.random.randint(0,50,10)
r

array([45, 10, 14, 37, 13, 41, 44, 10, 32, 44])

In [60]:
arr.reshape(1,5,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]])

In [61]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [63]:
ranarr=np.random.randint(0,50,10)
arr.reshape(5,5)  #max value gets changed every time
ranarr.max()

44

In [66]:
ranarr=np.random.randint(0,50,10)
arr.reshape(5,5) 
print(ranarr)#min value gets changed every time
print(ranarr.min())

[23  8  7 34  9 33  4 33 42  7]
4


In [ ]:
a=np.array([[1,3],[2,1]])
b=np.array([[2,2],[3,3]])


In [67]:
arr=np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [71]:
 arr=np.ones((4,4)) 
arr+2

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [82]:
arr=np.ones((4,4)) 
arr1=np.ones((4,4))
arr+1
arr1+2

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [95]:
a=np.arange(1,11)
a
a[4:]

array([ 5,  6,  7,  8,  9, 10])

In [5]:
#basic arithematic operation on numpy arrays
import numpy as np
a=np.arange(0,10)
print(a)
print(a+a)
print(a-a)
print(a*a)
print(a**a)
print(a*2)
print(a**3)
print(np.sqrt(a))




[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[0 0 0 0 0 0 0 0 0 0]
[ 0  1  4  9 16 25 36 49 64 81]
[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[ 0  2  4  6  8 10 12 14 16 18]
[  0   1   8  27  64 125 216 343 512 729]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [154]:
#indexing on multidimensional arrays
ar=np.array([[1,2,3],[4,5,6],[7,8,9]])
ar
ar[0]       # 1st rows
ar[2]       #3rd row
ar[0][2]
ar[2][2]
ar[1][2]
ar[1][0]
ar[2,:]

array([7, 8, 9])

In [157]:
arr= np.zeros((10,10))  # 10 rows and 10 columns
arr
rr=arr.shape[1]         # converting 2 dim to list or single shape
for i in range(rr):
    arr[i]=i
arr    

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [165]:
a=np.arange(12).reshape(3,4)
print(a)
for row in a:
    for colm in row:
        print(colm)
        

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
0
1
2
3
4
5
6
7
8
9
10
11


In [179]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
a3=np.array([[5,6,7],[8,9,10],[11,12,13]])
a4=np.array([[14,15,16],[17,18,19],[20,21,22]])
new_a=np.concatenate((a3,a4),axis=0)
print(new_a)
new_a1=np.concatenate((a3,a4),axis=1)
print(new_a1)


[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]
[[ 5  6  7 14 15 16]
 [ 8  9 10 17 18 19]
 [11 12 13 20 21 22]]


In [183]:
#split
a3=np.array([[5,6,7],[8,9,10],[11,12,13]])
np.array_split(a3,3)    #why do we need splitting?
                         

[array([[5, 6, 7]]), array([[ 8,  9, 10]]), array([[11, 12, 13]])]

In [185]:
#sorting
a3=np.array([[51,26,37],[89,9,101],[11,122,183]])
np.sort(a3)



array([[ 26,  37,  51],
       [  9,  89, 101],
       [ 11, 122, 183]])

In [186]:
a4=([20,5,8,33,6,51,26,37])
np.sort(a4)

array([ 5,  6,  8, 20, 26, 33, 37, 51])

In [189]:
#flip method
a3=np.array([[5,6,7],[8,9,10],[11,12,13]])
print(np.flip(a3))
a4=([20,5,8,33,6,51,26,37])
print(np.flip(a4))

[[13 12 11]
 [10  9  8]
 [ 7  6  5]]
[37 26 51  6 33  8  5 20]


In [193]:
#searching
a=np.array([1,2,3,4,5,6,7,8,9,10])
np.where(a%2==1)


(array([0, 2, 4, 6, 8], dtype=int64),)

In [9]:
import numpy as np
s=np.arange(1,11)
np.sin(s)
np.random.randint(0,11,5)
np.linspace(0,10,5)
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])